// Code generated by l10n-go; DO NOT EDIT.

package l10n

type Localizer interface {
	Hello(name string) string
}

var mapLangToLocalizer = map[string]Localizer{
	"en": en_Localizer{},
	"ru": ru_Localizer{},
}

var Supported = []string{
	"en",
	"ru",
}

func New(lang string) (loc Localizer, ok bool) {
	loc, ok = mapLangToLocalizer[lang]
	return loc, ok
}

func Language(loc Localizer) string {
	switch loc.(type) {
	case en_Localizer:
		return "en"
	case ru_Localizer:
		return "ru"
	default:
		return ""
	}
}