// Code generated by go-l10n; DO NOT EDIT.

package l10n

import "strings"

type en_Localizer struct{}

func (en_l en_Localizer) Hello(name string) string {
	var b0 strings.Builder

	b0.WriteString("Hello, ")
	b0.WriteString(name)
	b0.WriteString("!")

	return b0.String()
}