// Code generated by l10n-go; DO NOT EDIT.

package l10n

import (
	"strings"
	"strconv"
)

type en_Localizer struct{}

func (en_l en_Localizer) Hello(name int) string {
	b0 := new(strings.Builder)

	b0.WriteString("Hello, ")
	b0.WriteString(strconv.Itoa(name))
	b0.WriteString("!")

	return b0.String()
}