// Code generated by l10n-go; DO NOT EDIT.

package l10n

import "strings"

type en_Localizer struct{}

func (en_l en_Localizer) Hello(name string) string {
	b0 := new(strings.Builder)

	b0.WriteString("Hello, ")
	b0.WriteString(name)
	b0.WriteString("!")

	return b0.String()
}