// Code generated by l10n-go; DO NOT EDIT.

package l10n

import (
	"strings"
	"fmt"
)

type ru_Localizer struct{}

func (ru_l ru_Localizer) BankAccount(money float64) string {
	b0 := new(strings.Builder)

	b0.WriteString("На вашем банковском счету ")
	fmt.Fprintf(b0, "%+.3f", money)
	b0.WriteString(" рублей.")

	return b0.String()
}