// Code generated by l10n-go; DO NOT EDIT.

package l10n

import (
	"strings"
	"strconv"
)

type ru_Localizer struct{}

func (ru_l ru_Localizer) YouAreLate_minutes(b0 *strings.Builder, count int)  {
	switch {
	case count == 1:
		b0.WriteString("1 минуту")
	default:
		b0.WriteString(strconv.Itoa(count))
		b0.WriteString(" минут")
	}
}

func (ru_l ru_Localizer) YouAreLate(count int) string {
	var b0 strings.Builder

	b0.WriteString("Вы опоздали на ")
	ru_l.YouAreLate_minutes(&b0, count)
	b0.WriteString(".")

	return b0.String()
}