// Code generated by go-l10n; DO NOT EDIT.

package l10n

import (
	"strings"
	"strconv"
)

type en_Localizer struct{}

func (en_l en_Localizer) YouAreLate_minutes(b0 *strings.Builder, count int)  {
	switch {
	case count == 1:
		b0.WriteString("1 minute")
	default:
		b0.WriteString(strconv.Itoa(count))
		b0.WriteString(" minutes")
	}
}

func (en_l en_Localizer) YouAreLate(count int) string {
	var b0 strings.Builder

	b0.WriteString("You are ")
	en_l.YouAreLate_minutes(&b0, count)
	b0.WriteString(" late.")

	return b0.String()
}